---
- name: Install Postfix
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - postfix
      - postfix-pgsql

- name: "Configure Postfix {{ item }}"
  template:
    src: "{{ role_path }}/templates/etc/postfix/{{ item }}.j2"
    dest: "/etc/postfix/{{ item }}"
    mode: 0644
    owner: root
    group: root
  with_items:
    - "main.cf"
    - "master.cf"

- name: Verify Postfix
  service:
    name: postfix
    enabled: yes
    state: restarted

- name: Verify Postfix
  service:
    name: postfix
    enabled: yes
    state: started
